build-programmieraufgabe-pdf:
  image: "gitlab.informatik.hu-berlin.de:4567/ti/software/docker-paperbuilder/ubuntu1804:144dc62463072b1070e14313304a903b38f3bd90"
  script:
    - env -C CProgrammierung/aufgabenstellung latexmk

  # # though using `only` would be correct here, gitlab is broken as of now,
  # # so artifact download url gives 404 if this is only built on change
  # only:
  #   changes:
  #     - CProgrammierung/aufgabenstellung/programmieraufgabe.tex
  #     - CProgrammierung/aufgabenstellung/.latexmkrc

  artifacts:
    paths:
      - CProgrammierung/aufgabenstellung/programmieraufgabe.pdf
