############################################################
# Dockerfile that replicates the gcc-7 and glibc setup
# of gruenau5 as of July 2020
############################################################
FROM opensuse/leap:15.1
LABEL maintainer="stephaho@informatik.hu-berlin.de"
RUN zypper -n in gcc7
ENTRYPOINT sleep 200d
